name: arcticle_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.0-36.0.dev

dependencies:
  flutter:
    sdk: flutter
  ui_kit:
    path: packages/ui_kit

  cupertino_icons: ^1.0.8

  # State manager
  flutter_bloc: ^9.1.1
  logger: ^2.6.2
  bloc_concurrency: ^0.3.0

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4

  # HTTP
  http: ^1.6.0
  cronet_http: ^1.7.0
  cupertino_http: ^2.4.0

  # Utils
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SfPro
      fonts:
        - asset: packages/ui_kit/fonts/SF-Pro-Display-Regular.otf
        - asset: packages/ui_kit/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: packages/ui_kit/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: packages/ui_kit/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
