name: backend
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.11.0-36.0.dev

dependencies:
  drift: ^2.30.0
  firebase_admin: ^0.3.1
  logger: ^2.6.2
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  sqflite: ^2.4.2
  sqlite3: ^2.9.4

dev_dependencies:
  build_runner: ^2.10.4
  drift_dev: ^2.30.0
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
